In [2]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [3]:
#plt.style.use('seaborn-whitegrid')
plt.style.use('default')
#plt.style.use('bmh')

In [4]:
arr = np.arange(5)
arr

array([0, 1, 2, 3, 4])

In [5]:
np.save('my_array', arr)

In [6]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.load('my_array.npy')

array([0, 1, 2, 3, 4])

In [8]:
arr1 = np.load('my_array.npy')
arr1

array([0, 1, 2, 3, 4])

In [9]:
arr2 = np.arange(10)
arr2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.savez('ziparrayz.npy', x=arr1, y=arr2)

In [15]:
archive_arr = np.load('ziparrayz.npy.npz')
archive_arr

In [17]:
archive_arr['x']

array([0, 1, 2, 3, 4])

In [18]:
archive_arr['y']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
arr = np.array([[1,2,3,4],[4,5,6,7]])
arr

array([[1, 2, 3, 4],
       [4, 5, 6, 7]])

In [20]:
np.savetxt('my_tset_text.txt', arr, delimiter=',')

In [21]:
!cat my_tset_text.txt

1.000000000000000000e+00,2.000000000000000000e+00,3.000000000000000000e+00,4.000000000000000000e+00
4.000000000000000000e+00,5.000000000000000000e+00,6.000000000000000000e+00,7.000000000000000000e+00


In [23]:
arr = np.loadtxt('my_tset_text.txt', delimiter=',')
arr

array([[ 1.,  2.,  3.,  4.],
       [ 4.,  5.,  6.,  7.]])